/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scct;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;

import scct.Window.ManagerFinestra;

/**
 * Inizio della app (main class)
 * La gestione dell'interfaccia viene subito affidata ad altre classi.
 */
public class App {

    /**
     * Impostazioni di gioco globali.
     */
    public static class OPTIONS{
        private static boolean MUSIC_ENABLED = true;
        private static int MUSIC_GAIN = -18; //dB

        public static void toggleMusic(){ MUSIC_ENABLED = !MUSIC_ENABLED; }
        public static void setMusicEnabledSetting(boolean newSetting){ MUSIC_ENABLED = newSetting; }
        public static boolean getMusicEnabledSetting(){ return MUSIC_ENABLED; }
        public static void setMusicGainSetting(int newGain){ MUSIC_GAIN = newGain; }
        public static int getMusicGainSetting(){ return MUSIC_GAIN; }
    }

    private final ManagerFinestra windowman;

    App(){
        //Carica opzioni utente
        File opt = new File("game/options.txt");
        if(opt.exists()){
            try (FileReader fr = new FileReader(opt); BufferedReader buf = new BufferedReader(fr)){
                String options = buf.readLine();
                StringTokenizer tok = new StringTokenizer(options, ";");
                if(tok.hasMoreTokens()){
                    OPTIONS.setMusicEnabledSetting(Boolean.parseBoolean(tok.nextToken()));
                }
                if(tok.hasMoreTokens()){
                    OPTIONS.setMusicGainSetting(Integer.parseInt(tok.nextToken()));
                }
                buf.close();
                fr.close();
            } catch (IOException e) {
            }
        }else{
            try {
                opt.createNewFile();
                try (FileWriter fw = new FileWriter(opt)){
                    fw.write(OPTIONS.getMusicEnabledSetting() + ";" + OPTIONS.getMusicGainSetting());
                    fw.close();
                }
            } catch (IOException e) {
            }
        }

        //Inizializza finestra
        windowman = new ManagerFinestra();
    }

    private void start(){
        windowman.toggleShow();
        windowman.changeWindowType(0, null);
    }

    public static void main(String[] args) {
        new App().start();
    }
}
